import docx
myDocument=docx.Document('打折商品.docx')
#设置Word文件(myDocument)的第1节的页脚(注意：从第0节开始)
myDocument.sections[1].footer.is_linked_to_previous=False
myParagraph1=myDocument.sections[1].footer.paragraphs[0]
myParagraph1.text='这是第1节的页脚'
myParagraph1.alignment=docx.enum.text.WD_PARAGRAPH_ALIGNMENT.CENTER
myParagraph1.runs[0].font.size=docx.shared.Pt(16)
#设置Word文件(myDocument)的第2节的页脚
myDocument.sections[2].footer.is_linked_to_previous=False
myParagraph2=myDocument.sections[2].footer.paragraphs[0]
myParagraph2.text='这是第2节的页脚'
myParagraph2.alignment=docx.enum.text.WD_PARAGRAPH_ALIGNMENT.CENTER
myParagraph2.runs[0].font.size=docx.shared.Pt(16)
#设置Word文件(myDocument)的第3节的页脚
myDocument.sections[3].footer.is_linked_to_previous=False
myParagraph3=myDocument.sections[3].footer.paragraphs[0]
myParagraph3.text='这是第3节的页脚'
myParagraph3.alignment=docx.enum.text.WD_PARAGRAPH_ALIGNMENT.CENTER
myParagraph3.runs[0].font.size=docx.shared.Pt(16)
myDocument.save('我的Word文件-打折商品.docx')
