import openpyxl
myBook=openpyxl.load_workbook('房价表.xlsx')
mySheet=myBook.active
myLineChart=openpyxl.chart.LineChart()
myLineChart.add_data(openpyxl.chart.Reference(mySheet,
                          min_col=2,max_col=2,min_row=4,max_row=15))
myLineChart.set_categories(openpyxl.chart.Reference(mySheet,
                                    min_col=1,min_row=4,max_row=15))
#使用红色(FF0000)在折线图(myLineChart)上绘制折线
myLineChart.series[0].graphicalProperties.line.solidFill="FF0000"
#设置折线图(myLineChart)的折线宽度为15000
myLineChart.series[0].graphicalProperties.line.width=15000
#在折线图(myLineChart)的数据点上添加该数据点代表的数值
myLineChart.dLbls=openpyxl.chart.label.DataLabelList()
myLineChart.dLbls.showVal=True
#设置折线图(myLineChart)的数据点的图形符号为square
myLineChart.series[0].marker.symbol="square"
#设置折线图(myLineChart)的数据点的图形符号的填充颜色为红色(FF0000)
myLineChart.series[0].marker.graphicalProperties.solidFill="FF0000"
#设置折线图(myLineChart)的数据点的图形符号的边框颜色为红色(FF0000)
myLineChart.series[0].marker.graphicalProperties.line.solidFill="FF0000"
myLineChart.legend=None
myLineChart.title="使用折线图展示2018年度房价走势"
mySheet.add_chart(myLineChart,"C1")
myBook.save('结果表-房价表.xlsx')
