"""empty message

Revision ID: 08a61d19272d
Revises: 4620929272ed
Create Date: 2022-02-10 23:12:17.944502

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '08a61d19272d'
down_revision = '4620929272ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=50), nullable=False))
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'username',
               existing_type=mysql.VARCHAR(length=16),
               nullable=True)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
