"""empty message

Revision ID: 751e8b9f1d61
Revises: 08a61d19272d
Create Date: 2022-02-10 23:14:45.207244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '751e8b9f1d61'
down_revision = '08a61d19272d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('sex', sa.String(length=2), nullable=False))
    op.add_column('user', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'age')
    op.drop_column('user', 'sex')
    # ### end Alembic commands ###
