import openpyxl
myBook=openpyxl.load_workbook('房价表.xlsx')
mySheet=myBook.active
myLineChart=openpyxl.chart.LineChart()
myLineChart.add_data(openpyxl.chart.Reference(mySheet,
                         min_col=2,max_col=2,min_row=4,max_row=15))
myLineChart.set_categories(openpyxl.chart.Reference(mySheet,
                         min_col=1,min_row=4,max_row=15))
#设置在折线图(myLineChart)中不绘制折线
myLineChart.series[0].graphicalProperties.line.noFill=True
#设置折线图(myLineChart)的数据点的图形符号为diamond
myLineChart.series[0].marker.symbol='diamond'
#设置折线图(myLineChart)的数据点的图形符号大小为20
myLineChart.series[0].marker.size=20
#设置折线图(myLineChart)的数据点的图形符号的填充颜色值为915102
myLineChart.series[0].marker.graphicalProperties.solidFill="915102"
#设置折线图(myLineChart)的数据点的图形符号的边框颜色值为61210B
myLineChart.series[0].marker.graphicalProperties.line.solidFill="61210B"
#设置折线图(myLineChart)的样式为26
myLineChart.style=26
myLineChart.legend=None
myLineChart.title="使用折线图展示2018年度房价走势"
mySheet.add_chart(myLineChart,"C1")
myBook.save('结果表-房价表.xlsx')
